// look more into the purpose of this & significance of being able to "modify the initial HTML returned from the server"

import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Header from './_components/HeaderComp/header-state';
import Footer from './_components/FooterComp/footer-state';

// look into this
const inter = Inter({ subsets: ['latin'] });

// change !!
export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <Header />
                {children}
                <Footer />
            </body>
        </html>
    );
}
